### ISSUE TITLE
Make login after logout require fresh auth

### ISSUE THREAD

**Issue by 89oinotna** [kajarenc/stauthlib#5]
If i try to login after doing the logout im not prompted again to the oauth provider login, how can i force a fresh login?

**Comment by kajarenc** [comment]
Hello @89oinotna!
thanks for opening this issue!

in general, this is specified by the `prompt` parameter of client kwargs in `secrets.toml` provider section, and by default, we use the `select_account` option. 
However, you can always override that parameter for the concrete provider if it respects the `prompt` parameter. 

E.g. docs from Google and Microsoft, with corresponding values: 
https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters
https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#send-the-sign-in-request

E.g. for Microsoft to force user to login on each auth request you can specify this in your secrets:
```toml
[auth.microsoft]
client_id="your_client_id_here"
client_secret="your_client_secret_here"
server_metadata_url="https://login.microsoftonline.com/consumers/v2.0/.well-known/openid-configuration"
client_kwargs = { 'prompt' = 'login' }
```

Hope this will help!
Please let me know what identity provider you use
